### ISSUE TITLE
Transmutation Table Tablet. 

### ISSUE THREAD

**Issue by Dragonracer1973** [Skirlez/fabricated-exchange#2]
Unsure why, but in a pack I put together. ( I have a potatoes P.C.) The transmutation Table/tablet have no crafting recipe. Is this true or do I have a mod conflict somewhere. I am using 0.4.3 version of the mod. 
I also noticed Blocks such as Dripstone and Gravel have no  E.M.C. I presume I can set E..M.C. with commands as with Project E.?
Any plans on adding configuration access to the menu via Mod Menu?
Finally I have also notice  shift clicking on any item garners four stacks as opposed to one.

BTW I am glad you ported this as it was one of my fave forge mods. 
I also realize its a W.I.P.

**Comment by Skirlez** [comment]
- Table and Tablet recipes: I haven't made the crafting recipe for the Transmutation Table yet because I am still unsure if I want to change it from how it was in the original. As for the Tablet - I forgot to make one.
- Missing EMC: Not all blocks have EMC because I haven't had the time to set the EMC values for everything. You should see the [EMC Mapper wiki page](https://github.com/Skirlez/fabricated-exchange/wiki/The-EMC-Mapper) for commands on how to set your own values if you want.
- Mod Menu: I'll do it if it's possible to do in a way that doesn't force you to download Mod Menu. I'll look into it.
- Shift Click: That's a really odd issue? I'm assuming you're talking about the Transmutation Table here. When I do it, it gives me 1 stack. Could you send your pack to see if I can replicate it?

**Comment by Dragonracer1973** [comment]
File size is too big to send here. 
Here is a google drive link.
https://drive.google.com/file/d/1pvsUPB3_O_f4OsUuBOhdA0TS8XYAxnlH/view?usp=sharing

**Comment by Skirlez** [comment]
Downloaded it and tested. On my machine, as long as you held left click on any item offered in the Transmutation Table it would continuously give you items. I have narrowed down this behavior to https://modrinth.com/mod/inventory-profiles-next. Once removed, the Transmutation Table behaved like normal. Please test if removing the mod fixes it on your end and close the issue if everything works.

**Comment by Dragonracer1973** [comment]
yeah, that did. I look forward to future updates of this mod. Thanks for the timely response.

**Comment by Skirlez** [comment]
Thanks for opening the issue (:
